

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs :
  - job: First Job
  steps :
   - bash: echo build first job
   - job: Second Job
  steps :
   - bash: echo build second job

- stage: DevDeploy
  jobs :
  - job: DevDeploy Job
    steps :
    - bash: echo build first DevDeploy job
  - job: Second Job
  steps :
    - bash: echo build second DevDeploy job

- stage: QADeploy
  jobs :
  - job: QADeploy Job
    steps :
    - bash: echo build first QADeploy job
  - job: Second Job
  steps :
    - bash: echo build second QADeploy job

- stage: ProdDeploy
  jobs :
  - job: ProdDeploy Job
    steps :
    - bash: echo build first ProdDeploy job


